{
 "title": "My Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"node-exporter:9100\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15; A:",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(avg by(instance) (node_load1{instance=~\"node-exporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"node-exporter:9100\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(avg by(instance) (node_load5{instance=~\"node-exporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"node-exporter:9100\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(avg by(instance) (node_load15{instance=~\"node-exporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"node-exporter:9100\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance) (100 * ((avg_over_time(node_memory_MemFree_bytes{instance=~\"node-exporter:9100\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\"node-exporter:9100\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"node-exporter:9100\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"node-exporter:9100\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"node-exporter:9100\",mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=~\"node-exporter:9100\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}